# Generated by Django 3.2.5 on 2021-07-14 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created by')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified by')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('address_number', models.IntegerField(blank=True, null=True, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='complement')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='district')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('country', models.CharField(blank=True, default='Pakistan', max_length=50, null=True, verbose_name='country')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=11, null=True, verbose_name='RG')),
                ('cnh', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('exist_deleted', models.BooleanField(default=True, help_text='If True the item exists. If it is False the item has been deleted.', verbose_name='exists/deleted')),
                ('first_name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'ordering': ('first_name',),
            },
        ),
    ]
